Add codemagic yml

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -1,48 +1,141 @@
 workflows:
-  ionic-app:
-    name: Ionic App Workflow
-    max_build_duration: 60  # Duración máxima en minutos
+  ionic-capacitor-ios-workflow:
+    name: Ionic Capacitor iOS Workflow
+    max_build_duration: 120
+    instance_type: mac_mini_m2
+    integrations:
+      app_store_connect: codemagic
     environment:
-      node: v18.0.0  # Especifica la versión de Node.js (puedes ajustar según la que necesites)
-      xcode: latest  # Si es necesario compilar para iOS, define la versión de Xcode (latest o especifica la versión)
+      ios_signing:
+        distribution_type: app_store
+        bundle_identifier: io.codemagic.ionicsample
       vars:
-        # Variables de entorno si necesitas para la firma del APK
-        RELEASE_KEYSTORE: 'I_AM_NOT_A_VALID_KEY'
-        RELEASE_KEYSTORE_PASSWORD: 'I_AM_NOT_A_VALID_KEY'
-        RELEASE_KEY_ALIAS: 'I_AM_NOT_A_VALID_KEY'
-        RELEASE_KEY_PASSWORD: 'I_AM_NOT_A_VALID_KEY'
-
+        # Ionic Xcode worskspace and scheme
+        XCODE_WORKSPACE: "App.xcworkspace"
+        XCODE_SCHEME: "App"
+        APP_STORE_APP_ID: 1555555551 # <-- Put the app id number here. This is found in App Store Connect > App > General > App Information
+      node: v16.11.1
+      xcode: latest # <-- set to specific version e.g. 14.3, 15.0 to avoid unexpected updates.
+      cocoapods: default
+    triggering:
+      events:
+        - push
+      branch_patterns:
+        - pattern: develop
+          include: true
+          source: true
     scripts:
-      - name: Instalar dependencias
+      - name: Install npm dependencies for Ionic project
         script: |
-          npm install  # Instala las dependencias de la aplicación Ionic
-          npm install -g @ionic/cli  # Instala Ionic CLI globalmente
-          ionic info  # Verifica la configuración de Ionic y su entorno
-
-      - name: Compilar para Android
+          npm install
+      - name: Cocoapods installation
         script: |
-          ionic build  # Construye la aplicación web
-          npx cap sync android  # Sincroniza con Capacitor para Android
-          cd android && ./gradlew assembleRelease  # Genera el APK de Android en modo release
-
-      - name: Compilar para iOS
+          cd ios/App && pod install
+      - name: Update dependencies and copy web assets to native project
         script: |
-          ionic build  # Construye la aplicación web
-          npx cap sync ios  # Sincroniza con Capacitor para iOS
-          xcodebuild -workspace ios/App/App.xcworkspace -scheme App -configuration Release  # Construye la aplicación iOS en modo release
-
+          # npx cap copy # <- use this is you don't need to update native dependencies
+          npx cap sync # <- update native dependencies and copy web assets to native project
+      - name: Set up code signing settings on Xcode project
+        script: |
+          xcode-project use-profiles
+      - name: Increment build number
+        script: |
+          cd $CM_BUILD_DIR/ios/App
+          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_ID")
+          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
+      - name: Build ipa for distribution
+        script: |
+          cd $CM_BUILD_DIR/ios/App
+          xcode-project build-ipa \
+            --workspace "$XCODE_WORKSPACE" \
+            --scheme "$XCODE_SCHEME"
     artifacts:
-      - android/app/build/outputs/**/*.apk  # Especifica el APK generado para Android
-      - ios/build/**/*.app  # Especifica el artefacto de iOS generado
-
+      - build/ios/ipa/*.ipa
+      - /tmp/xcodebuild_logs/*.log
+      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
+      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
     publishing:
-      scripts:
-        - name: Subir APK a Google Play
-          script: |
-            # Subir el APK generado a Google Play con Fastlane
-            fastlane supply --apk android/app/build/outputs/apk/release/app-release.apk --track beta --json_key path/to/google_play_key.json --package_name com.yourapp.package
+      email:
+        recipients:
+          - user_one@example.com
+          - user_two@example.com
+        notify:
+          success: false     # To not receive a notification when a build succeeds
+          failure: false     # To not receive a notification when a build fails
+      app_store_connect:
+        auth: integration
 
-        - name: Subir a TestFlight (iOS)
-          script: |
-            # Subir el IPA generado a TestFlight con Fastlane
-            fastlane pilot upload --ipa ios/build/Release-iphoneos/App.ipa
+        # Configuration related to TestFlight (optional)
+        # Note: This action is performed during post-processing.
+        submit_to_testflight: true
+        beta_groups: # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
+          - group name 1
+          - group name 2
+
+        # Configuration related to App Store (optional)
+        # Note: This action is performed during post-processing.
+        submit_to_app_store: false
+
+
+  ionic-capacitor-android-workflow:
+    name: Ionic Capacitor Android Workflow
+    max_build_duration: 120
+    instance_type: mac_mini_m2
+    environment:
+      android_signing:
+        - keystore_reference
+      groups:
+        - google_play # <-- (Includes GCLOUD_SERVICE_ACCOUNT_CREDENTIALS <-- Put CONTENTS of your Gloud crendentials file here)
+      vars:
+        PACKAGE_NAME: "io.codemagic.ionicsample"
+        GOOGLE_PLAY_TRACK: alpha
+      node: v18.0.0
+    triggering:
+      events:
+        - push
+        - tag
+        - pull_request
+      branch_patterns:
+        - pattern: develop
+          include: true
+          source: true
+    scripts:
+      - name: Install npm dependencies for Ionic project
+        script: |
+          npm install
+      - name: Set Android SDK location
+        script: |
+          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
+      - name: Update dependencies and copy web assets to native project
+        script: |
+          # npx cap copy # <- use this is you don't need to update native dependencies
+          npx cap sync # <- update native dependencies and copy web assets to native project
+      - name: Build Android release
+        script: |
+          LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
+          if [ -z LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
+            # fallback in case no build number was found from Google Play.
+            # Alternatively, you can `exit 1` to fail the build
+            # BUILD_NUMBER is a Codemagic built-in variable tracking the number
+            # of times this workflow has been built
+            UPDATED_BUILD_NUMBER=$BUILD_NUMBER
+          else
+            UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
+          fi
+          cd $CM_BUILD_DIR/android
+          ./gradlew bundleRelease \
+            -PversionCode=$UPDATED_BUILD_NUMBER \
+            -PversionName=1.0.$UPDATED_BUILD_NUMBER
+    artifacts:
+      - android/app/build/outputs/**/*.apk
+    publishing:
+      email:
+        recipients:
+          - marc.pascual@colaboradorholaluz.com
+        notify:
+          success: true
+          failure: false
+      google_play:
+        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
+        track: internal
+        submit_as_draft: true
